### ISSUE TITLE
設計など

### ISSUE THREAD

**Issue by pyama86** [takumakume/max_clients_handler_cli#1]
気になったことをつらつらと。

1. [mruby-cli](https://github.com/hone/mruby-cli/blob/master/mrblib/mruby-cli.rb)のようにコマンドごとにクラスを分けるとスッキリかけそうです。

2. https://github.com/takumakume/max_clients_handler_cli/blob/master/mrblib/max_clients_handler_cli/initialize.rb#L7

モジュール全体で使うのであれば、設定情報はモジュール変数に持てせてはいかがでしょう。

3. [このような場合](https://github.com/takumakume/max_clients_handler_cli/blob/master/mrblib/max_clients_handler_cli/initialize.rb#L10)はraiseしてよさそうに思えます

4. [メソッド化すれば同じような処理がいらなくなりそうですね](https://github.com/takumakume/max_clients_handler_cli/blob/master/mrblib/max_clients_handler_cli/initialize.rb#L17)

全体的に、`if`、`unless`、`begin〜rescue`が異常に多いのはなぜなのかを考えるとよいコードになりそうです。

**Comment by takumakume** [comment]
コメントありがとうございます。
全体的に似たようなエラー処理が多く、設計から見直したいと思います。
ありがとうございます！
